services:
    identityprovidersystem-logger:
        image: datalust/seq:latest
        container_name: identityprovidersystem-logger
        ports:
            - "5342:80"
        environment:
            ACCEPT_EULA: "Y"
        restart: unless-stopped
        networks:
            - base-network
    identityprovidersystem-api:
        build: ./IdentityProviderSystem.API
        container_name: identityprovidersystem-api
        environment:
            DatabaseServer: "mssql-server"
            DatabasePort: "1433"
            DatabaseUser: "sa"
            DatabasePassword: "Password.1234"
            DatabaseName: "IdP_DB"
        depends_on:
            - identityprovidersystem-logger
        ports:
            - "8081:8080"
        networks:
            - base-network

networks:
    base-network:
        external: true